### PR TITLE
Adding support for others charset, CP1047 as fallback

### PR DESCRIPTION
**Pull request by CharlesDUBOIS**
Hi,

I'm opening this request to allow others people to specify their charset. 

I've encountered this issue while experimenting on a French system with some obviously French characters which are included in the charset CP1147.

I don't know if I have listed all the charsets supported by the original TN3270, but it seems to be good enough for me.

PS: Please be kind, it's my first Pull Request :)
PS2 : If I've made some grammatical mistake, be kind too, i'm French and not used to write in English (like every French ;)  )

My regards

### CODE REVIEW

**Comment by rabelenda** [comment]
First of all, thank you very much for your contribution. We really appreciate contributions. 

There are only 2 things we would like to have before merging your request:

- Would be nice to avoid using a singleton for hosting the charset, and make the charset a property of the TerminalClient/connection/screen, etc. This way a given JVM application may use different connections with different charsets (singleton does not allow that). 
- Would also be nice to have at least one TerminalClientTest test using an alternate charset to verify and demonstrate the proper working of the functionality. It can be a really simple flow, eg: just displaying a connection welcome screen that has french characters. What we have done for other tests to generate the associated dumps is using [wireshark](https://www.wireshark.org/) to capture the traffic between a terminal emulator and a mainframe application (it can be for your case just connecting to the mainframe app and waiting for welcome screen), then we save captured tcp traffic as json, then we use [wiresham](https://github.com/abstracta/wiresham) to convert the dump to a reduced yaml (removing any reference to ips, and lower level details), and then with the aid of wireshark packet visualization and [CyberChef](https://gchq.github.io/CyberChef/) modify the dumps to change (with dummy data) all potentially sensitive information (if any). Additionally, some times we add a client packet at the end of dump waiting for FFFF (that is never sent by clients) to avoid wiresham to close the connection when it reaches the end of flow.

We can help you with the first part (how to avoid using the singleton). Sadly we can't help with the second one since we don't currently have access to a mainframe application using an alternate charset. Let us know if you can tackle the second one and if you need help with the first one. Some examples of tests can be found in previously mentioned TerminalClientTest class and in particular shouldGetWelcomeScreenWhenConnect method waits for a welcome screen to be an expected one (your test should be identical but changing expected screen and changing flow to load like is done with setupExtendedFlow method).

Regards, and thank you again for the contribution, we are eager to include this change for all the community to take benefit from it.

**Comment by CharlesDUBOIS** [comment]
Thanks for you reply, i didn't think about the multiple instanciation of `TerminalClient`.

I'm currently extracting the charset management inside a class, but I experience some difficulties to extract the `toHex` method of `Dm3270Utility` which has a reference to the charset.

In your opinion, should I pass the reference to all classes that use this method or should I let this method as it was before my request cause it's only used in log or toString method? Tell me if you think about a third option.

In addition, thanks for the method to test it, I was thinking about it, but I didn't knew the correct way to get the Telnet traffic. 
It is especialy usefull to me cause I wanted to wrote some unit test on the project i'm working on, and so it's a big thank you.

My regards.

**Comment by rabelenda** [comment]
Hi, based on your great contribution and to ease your work we have created [MULTI_CHARSET branch](https://github.com/Blazemeter/dm3270/tree/MULTI_CHARSET) with a proposal to avoid the singleton and done some refactoring for some cleanup. If you want you can take the code from there for this pull request, or send a pull request to that branch adding the test to it. We will wait for a test to merge any of the the branches.

I am glad you can use the tips I gave you for implementing the tests on other projects. I would advice you taking special attention to [wiresham](https://github.com/abstracta/wiresham) documentation which allows you to create test doubles of mainframe applications for easy and fast tests of mainframe application client conde, and check [this webinar](https://youtu.be/Sr1BOi50xqg) which introduces testing mainframe applications through jmeter and in particular creating a test double with wiresham.

Regards, and thank you again for the effort you are taking and the contribution. We are anxious to get that test and release this feature to the community.

**Comment by CharlesDUBOIS** [comment]
Hi,

I managed to add tests with all the pieces you gave me, but I had to start over your MULTI_CHARSET branch cause it was better written than my branch and in fact due to the singleton i couldn't change the charset inside tests and it took me quite a time to see it. I'll close this request and open another one on the MULTI_CHARSET branch to add the tests.

Thanks for your time and your tips, especially on wiresham, hopefully this will the community.

My regards

**Pull request closed without merging**
